FROM cimg/base:stable-20.04

RUN sudo apt-get update -y
RUN sudo apt-get install -y python3.9 python3.9-venv python3-pip
RUN sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
RUN sudo ln -sf /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install jinja2=="3.0"
RUN python -m pip install pyyaml=="6.0"
RUN python -m pip install "pipenv==2022.1.8"
